name: Update Commit Count
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: scripts
        run: yarn

      - name: Update Commit Count
        working-directory: scripts
        env:
          GIT_PAT_TOKEN: ${{ secrets.GIT_PAT_TOKEN }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          BLACKLISTED_REPOS: ${{ secrets.BLACKLISTED_REPOS }}
          BLACKLISTED_ORGS: ${{ secrets.BLACKLISTED_ORGS }}
          KV_URL: ${{ secrets.KV_URL }}
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
          KV_REST_API_READ_ONLY_TOKEN: ${{ secrets.KV_REST_API_READ_ONLY_TOKEN }}
        run: |
            node --no-warnings update-commit-count.js
